# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-04-09 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=32)),
                ('b_risk', models.TextField()),
                ('b_level', models.CharField(max_length=32)),
                ('b_details', models.TextField(max_length=32)),
                ('b_repair', models.TextField()),
                ('b_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BugModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=32)),
                ('b_risk', models.TextField()),
                ('b_level', models.CharField(max_length=32)),
                ('b_details', models.TextField(max_length=32)),
                ('b_repair', models.TextField()),
                ('b_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=32)),
                ('p_time', models.CharField(max_length=32)),
                ('p_charge', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='bug',
            name='b_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.Project'),
        ),
    ]
